name: Jest
on: 
  push:
    paths:
    - 'jest/**'
    - '.github/workflows/jest.yml'

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: install
        run: npm install
        working-directory: jest
      - name: run jest
        run: npm run test
        working-directory: jest
