name: Environment
on: 
  push:
    paths:
    - 'environment/**'
    - '.github/workflows/environments.yml'

jobs:
  development-development:
    runs-on: ubuntu-latest
    steps:
      - name: development echo
        run: echo "hello development"
  deployment-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Set Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: production copy
        run: node index.js
        working-directory: environment
