name: Go
on: 
  push:
    paths:
    - 'go/**'
    - '.github/workflows/go.yml'

env:
  RUN_TEST_ON_GITHUB_ACTIONS: 1

jobs:
  unit-test-ubuntu:
    name: Run go(unix)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.x'
      - name: Run go
        run: go run main.go
        working-directory: go
  unit-test-win:
    name: Run go(win)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.x'
      - name: Run go
        run: go run main.go
        working-directory: go
