name: Go
on: 
  push:
    paths:
    - 'go/**'
    - '.github/workflows/go.yml'

jobs:
  unit-test:
    name: Run go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.x'
      - name: Run go
        run: go run main.go
        working-directory: go
