name: Jest
on: 
  push:
    paths:
    - 'jest/**'
    - '.github/workflows/jest.yml'
    branches:
      - main

jobs:
  unit-test:
    name: Run Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install Dependencies
        run: npm install
        working-directory: jest
      - name: Run Jest
        run: npm run test
        working-directory: jest
