name: Node
on: 
  push:
    paths:
    - 'node/**'
    - '.github/workflows/node.yml'

jobs:
  unit-test:
    name: Run node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Set Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run node
        run: node check.js
        working-directory: node
