name: Shell
on: 
  push:
    paths:
    - 'shell/**'
    - '.github/workflows/shell.yml'

jobs:
  shell:
    name: Run shell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run shell
        run: ./index.sh
        working-directory: shell
